Add compare test

diff --git a/.github/workflows/get-diff-test.yaml b/.github/workflows/get-diff-test.yaml
--- a/.github/workflows/get-diff-test.yaml
+++ b/.github/workflows/get-diff-test.yaml
@@ -29,7 +29,17 @@ jobs:
       - name: test
         run: |
           ./gradlew roborazzi-gradle-plugin:build --stacktrace
+          echo '<resources><string name="first_fragment_label">This is verify test screen! Verify me!</string></resources>' > app/src/main/res/values/strings_for_test.xml
           ./gradlew app:compareRoborazziDebug --stacktrace
+          // Check if there are difference with app/build/outputs/roborazzi/test_compare.png
+          file_path="app/build/outputs/roborazzi/com_github_takahirom_roborazzi_sample_ManualTest_captureRoboImageSample_compare.png"
+          if [ ! -f "$file_path" ]; then
+            echo "Error: File $file_path not found."
+           exit 1
+          else
+            echo "File $file_path found."
+            exit 0
+          fi
 
       - name: verify test
         run: |
